// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddProductPrice : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207061350352_AddProductPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy8up8erVVlMs5ZQ2R3LGx+lx2WRETav8/L8PVHbeQjUPrKdUrenhF57/eZ6lXPXn330sq5m62nrN6Jmv1d+HXxAH1HDVV6316/yc3317OlH6d3wvbvdF+1r3jvonX5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNc3M2yxl7pcKj1ae3I8TDuzt7IMTdbLmsWqZuD/EOmvjXIPq6rYlnPkqfFe/y2fN8edHOLbJfZO/MJ/TrR+lXy4JYjF5q63XuD07+3tzpy7qY2l6f5tNikZUfpS9r+k2Z+OCj9PU0A7wY5Xzoj++6me7PP7FlmxVEX+2ZCf50go/zd11ekFde523IMcSZrgthz7FhpigqtlMnBHdFCoy03B0Ql8dfZKsVzYEnPvpJ+lpk52T79fvLxkJg3J02ERGx2NqeiEbZRd75lromTJ8VddM+zdpskmEiTmaLXrPbkdh01qF0VxYd4c0L+F1eiqsROzUdUI6Uz2h0CxIwHqgOkzAa0BD6LrgxqyMyflKV68VySE9seltEz39fPrk9BJUjH4R+1Ifx+G5n+F1Se3KkLTsarzt3mzi/28T2biWgw+mPletuth49NpQm0B/VZTFjFrxu2nwxRoPx619UnpQFjdc1+CJbFud5"
                       + "076p3uawhCQlX9/4WJ3bNLPy/6UWqMDob7Q1G9VsH7xvOZaXWT2dZ/XWInt354OsweyHaQ36Gu1WBmGTPRBmpHFMKhqS4OnsyNe0Fn3ZeHzX978eP82b4sKBgDe2zKdQiw6oaXO2PK/MDNDQfIxMk84EfZG32YwodFy3xXk2benrad407Cv8ZFauqcnpYpLPzpZfrtvVuj1umnwxKa/98T6+u7l/Nokhzo+/XOEvTxl8/SEQmgUNIf9y+WRdlDOL97MICw2AALOo+BBW5CsRuItrC+lFtbwlICXf03yVLyF8b/LFqiRgzZfL19llPozbzTQMKfb4aZFd1NmiURjuffqT2I+c+aP/JwAA//8HwKkNQQwAAA=="; }
        }
    }
}
