// <auto-generated />
namespace CavanGaelsCarRentals.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207261021175_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5PsMlt+nlGrk6x+lS/brGzGT7M2O55O86b5KD0ui4zQep2X5++J485D4PiR7Z36PyU82+s316uccUD3td+Amvxe+XXwAX30sq5Wed1ev8rP9bWz2Ufp3fC9u90X7WveO+iZflu29/Y+Sl+syzKblPTBOQ06/yhdffrodVvV+ef5Mq+zNp+9zNo2r5d4N2fMlQKPVp/ejggP7+7sgQh3s+WyarOWZruHeAfNaVb//nV+YXB93dbEOx+lz4p3+ex5vrxo5xbfL7J35hP69aP0q2VBrEYvtfU698cnf2/ut6ymit8PueNp1bS/P33w+8+ya9P503xaLLLyo/RlTb+pMB18lL6eZgAbm7zNnbxer1Zlkdc3M0EHzovssrhgwgxA/Ch9lZfcoJkXKxGUsfny9yf+Jhl6VleLV1XpvcVf/P5vsvoibwmjKvbt62pdT98DoydV9ZamrIlipF8Cso+P93EPG/+798XlqyXplQKULco8ipBrkXeR6nzVQ6z7fQy5x3edrtmogew8/kgN+WgSsKL8oeuCH54SGuRckdivL9OGGeMybVj5a7GqCuSPOPX/BZw6UeU4rcj3ek+b0gE1I8pZw0e/vyFX7r2BnKybtlp8DQPXZ//3BjEsS4pUVJ7Ml7+/s1tOpnpf9oxAv8X7"
                       + "2ii2Ol/PVHaFPGZGv5aIW4r9SMb/vy3jX89Le0+Z6LLhsNR8LWb0/Kwf8WOAZp1nTbX8/dv8neWLHxpXNm1Wt7//N2I08uXsmwH0zVqNAb38HhFDVzCGIorbiMVx01TTgpHphAziCYajOl3O0o1uoTCL71ASf6zLtqDfp9Q9BbohSAL65fJpXuZtnh5PgQZI1EyzWZ+mNITZ7fCx5tThwzQNUflWrwcS77yGnGUlpZmats6KZdvXBcVyWqyychMpOi/dUoVgkBZ895un+YpYmrDbNOTb9OunC/r92246xL+JNo/very0mcX6hmBoWjdYBW9qrSP2Q2G1Dd6bw8lEMz87LDdIlttM/wey3eDwb9O378j/nLCe7/4OTXDUF/4aUxuHeDvd9I3y7tfisRDnW8/wB3JXhPa36VVN9M8JS3Ut9xATDJpxxwi+T/oe7DWYUvx/OYsN4H2bCf9ANhuYi9v0/MNjNfHY6J2W3shr7f/ppMdhaPY6bx2CFFk5d8/ngB4Lha8azyD2vnPobgDiorseDKs6bwBhzER0HNba3wDEznFRFm2Rx2AF8tYB501Kn0CaJvXaRPOoXR65yX+2QwimosdqN7m9HhjBsyu+4dhuMe5I6N4f+w1uXYD4sGPnI+/YYAMNhv0xD5TD+4NpEWTQ+lQY9DACpGM+xi3QHYTxszf1KiMuMO0PeaMFDFAesoEe2n2x3UCCIcv39clgAmWrdu13j+++5kSLfvD4LjWZ5qt2nZVfUL6jbMwXX2SrFSbPvamfpK9X2RQcu/1a0zi3y+Ec3KU0zkJg3J0GYtU1ErYnyiJlF3nnW+qaMH1W1E1L2ZBskiFzcTJb9JoNGxnTgWdr+tNj1KxpjN/NC5fZ8vOMqEWvviKrSNmTMXA5nk7zphlH2MfR7xkNaQEjzjmycI77b9F7WFHP6kgW7qQq14vlsCsx/PaUuKzOL0IQ9sPbw3GLgT4g9+ntIU2rpv396QNKdl130Aq+uT1E"
                       + "P0Hgw9uUOIBAdKapyxdeCkpbdoSyy2S3YkFnKL9JPowvnDPYm5hx+NWfHY7U5QMfgH50exjvz40/R7O9wbX4+pNt3NL3n+vBN//fO9WddR8fVuer28OUNLsPSj65PQQ/MeTD2ZQw2gAt6wOKh20/Z4zsfNtvkpPjK6wM9kYbOvjq/z95+edo3nvu7Tc5/YNrmgz5Jg7Y+PbPDhMES40+mOCL28Pzlw99cP7nt4eW2xXEgEvtp7eH9P8ahdQLb7pNbO/6if3bhjcaWnzhxzw8bkQwPN5Gw5xurCFNPkqJOJfFDHHG6+umzRfMwuPXv6g8Ib8J0moafJEti/O8ad9Ub3MKNhEKUfxZFlkjked7RVF2JbxpZmUkhgI93XR14p/u0n56u6Tk47vdF7uLy3hHMlIFRn7j6v97rl3byET6WF5m9XSe1VuL7N2d91ibZ1jOHfwGgIWxiQCc5dNikZWYf/qt4QTDLs04RIq+vsWy+4ZAxiPyRihDK+U9Jon7+f+f5RQ1vt/A1H4An9ya+FHH+0e077o9t2X6PiCxcCqX9HtbLPL3BuJ7718fFbWUtwVwax6Ke7w/YqKvy0S3Jvygo/n/WdoH7uo3MAO+v/qBMujc1Q8E9A2JYX8BfcOaWWSpK1jWdh9+8bO3tu0tNWVh9/x32HN/nf5rLY1vyD/eRiAwjlsvhsdz7v1uNqV/fxaWv/uMcsMCY2RNMJwt++EPhVnsYreHgv3sZ4VpNmR/vnGmGc6Z9rvalMT7oTDO4Jrs+8n2/38Y5ZYS/8PkkXg65IfCHhvXr/9fwSK+x+RjEHz+s8oq/ph+Flhlc+by55JdxIux+TLTf28dvTt1moJz+H6UOofIZyDJipFjNqlobsWfYk+oyyBdmM756QF2X8WguyXTm7qwaqjXg/0m1oG1zzfBdya5Txv7VZRAdvnkpi4CEen1Enwb68hr0O/LY5n+tIg7m3ptOpMT8XcDoe/Ob7i63Of9jqLyXuK/u+om"
                       + "RP4WA+u7X5HB3eCjhWh2Zj9ch9o0wA5fBmuxHz5Q312IDHHQm3jfOfghDqlr4iLD2mgFP2hoERHsLTjdfoi9JQz73eO7IsH6Af3ZW6ogQ7BeIvyVv57mTXHhQDwmmMuc7bQDatqcLc8rY4g6GJkmnYj5i7zNZlidq9viPJu29DWW6XhGfzIr19TkdDHJZ2fLL9ftat3SkPPFpLz2iQGLtqn/x3d7OD/+coW/vLWZrz8EQrOYZW3+5fLJuihnFu9nkYB/AARMpaZaMJctUi4X1xbSi2p5S0BKvqfGwr/JF6uSgDVfLl9nl/kwbjfTMKTY46dFdlFni0ZhuPfpT2K/2eLd0f8TAAD//7ZRkloQSQAA"; }
        }
    }
}
