// <auto-generated />
namespace CavanGaelsCarRentals.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddUnavailableToBookingAndCars : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207271516417_AddUnavailableToBookingAndCars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5PsMlt+nlGrk6x+lS/brGzGT7M2O55O86b5KD0ui4zQep2X5++J485D4PiR7Z36PyU82+s316uccUD3td+Amvxe+XXwAX30sq5Wed1ev8rP9bWz2Ufp3fC9u90X7WveO+iZflu29/Y+Sl+syzKblPTBOQ06/yhdffrodVvV+ef5Mq+zNp+9zNo2r5d4N2fMlQKPVp/ejggP7+7sgQh3s+WyarOWZruHeAfNaVb//nV+YXB93dbEOx+lz4p3+ex5vrxo5xbfL7J35hP69aP0q2VBrEYvtfU698cnf2/ut6ymit8PuWMMeJG9zX9uOoaA/NB7Xq4Xk7z+/avz33+VNQ2BJUVwE3PeMHvri4vsIv/9Wap/6OMpFuh7Xf/wKTmtmvb3pw9+/1l2bTp/mk8JIcLlZU2/qSY++Ch9Pc0A9v2J+3q9WpVFXt+sQTpwXmSXxQVL1QDEj9JXeckNmnmxEi07Nl/+/qQciS2e1dXiVVV6b/EXv/+brL7IW8Koin37ulrX0/fA6ElVvaUpa6IY6ZeA7OPjfdzDxv/ufXH5aklGqQBlizKPIuRa5F2kOl/1EOt+H0Pu8V1nqDaaLzuPP7JhPpoErPjh64IfngUb5FyR2K8v04YZ4zJtWPlrsaoK5I849f8FnDpR5TityHF/"
                       + "T5vSATUjylnDR7+/oTjgvYGcrJu2WnwNA9dn/w8F4ann9wY1LJY6vqhomi9/f2cCnXj2vuzZk36L9zV3bMC+ntXt6ouYRb4tGh7lN6ITtOuj5dvXIfT8Nh+k1OzE/kir/X9bq309v/Q9RbfLjsPC/bWY0ReMH/Gjj2adZ021/P3b/J3lix8aVzZtVre//zdiJvPl7JsB9HXs5Hubj/eIkbqCMRRD3UYsjpummhaMTCdIEt83HNXpcpZudISFWXwXmvhjXbYF/T6l7im0D0ES0C+XT/Myb/P0eAo0QKJmms36NKUhzG6Hj7X6Dh+maYjKt3o9kHjnNeQsKykr27R1Vizbvi4oltNilZWbSNF56ZYqBIO04LvfPM1XxNKE3aYh36ZfP0HS79920yH+TbR5fNfjpc0s1jcEQ9O6wSp4U2v9xfdgta/PahucTIeTid9+dlhukCy3mf4PZLvB4d+mbz90+TlhPd9LH5rgqMv+NaY2DvF2uukbVZNfi8ciON9mhj+QuyK0v02vaqJ/Tliqa7mHmGDQjDtGCIK127PXYBL1/+UsNoD3bSb8A9lsYC5u0/PPJavFgvqbdE40wv9GtFksL3A7Zv65Z70n1eAYbsMEH8h+G+bmNr13sm4/BFaU4IHeaemNvFY8nk563Idmr/PWyQoF+S7y8JVRj73CV42TGnvfxRY3AHGJhh4My/c3gDAeS3Qc1vG8AYidsKIs2iKPwQqkpQPOm5Q+gXSNwmvToVIkkAvEOR7K2SEEU9FjtZsiMA+M4NkV53Bstxh3JIvUH/sNEUaA+HCM4SPv2GADDYZDAw+Uw/uDaeF7sxEqDDq7UXXu+yS3QHcQxs/e1PdyJP0hb3TGApSH3DEP7b7YbiDBkBP2zZMh5gVsmP1BZyE6gzF34etyQ8xBeA/ybiCNSWdZi2S/e3z3NadD9YPHd6nJNF+166z8grKSZWO++CJbrTAS96Z+kr5eZVMI8/ZrTbbeLtN6cJeSrQuB"
                       + "cXcaaJyu/bQ9Ua43u8g731LXhOmzom5ayllmkwz5xZPZotds2P6aDjwz3J8uY4FMY/xuXrjMlp9nRC169RU5DJTjHAOX4+k0b5pxRLIc/Z7RkBbwdTiTHbJ//y167/U0K7M6kis/qcr1YjnscQ2/PSUBrPOLEIT98PZwymqqKXMfkPv09pDQ+SJ7m/dRkk/fExJYOQJKPr49rOV6MSFzVZ3//qusaSiLzxbOBxtvcfseyvXFBbH4799AqDpkDL+6PcxigdfWdYcC3se3hzWtmvb3pw9oqeC6Q9Dgm9tD9NOrPrxNaVcoqo74dOXVS+Bry46y7Ar/rVSD8+2+Sf1gHfT3VxLDr/7saApdfPUB6Ee3h/H+WuLnaLY3eMNff7JNJPX+cz345s/+VH/dqZ6oa6Or5v58d766PUxZpPRBySe3h+Cn1X04m9LtG6BlfUDxpNcwjE6Kwod1Q/bi50w4XIj3TUqHzRG8v3gMv/r/T/n4OZr3XhjyTU7/huDrFhyw8e2fHSao86yplr9/m7/rTF/wxe3hNW1Wt79/X8X5n98eGmU1I7Dcp7eH9D5K7meVMXuhbLeJ7V0/sX/bUFbDyC/8+JbHjWiVx9toSNuNK6XJRykR57KYIaZ8fd20+YJZePz6F5Un5ItBWk2DL7JlcZ437ZvqbU6JBoS9lHsoi6yRrMN7RcwP7+7s3c1ni7tNMysj8TLo6aarE+v+Xvl1dxpuk6d/fLf7on3Ne0cSswVGzjL5eU4TQxw2e5m1bV4v0SpnHD9KX6xLltDPPjon4e9nb4dCU+ljeZnV03lWby2yd3d8YG29vhGWczG/AWAuFv2mgEk0+g1Aiweh3iS95xx0Is9vAEMv9vwGoIWhpwCc5VPqpIQo0m8N5/l2Sfig3ejrvfcmgh+P3paUvqbbKK/xMO7/s0KrftA3MLUfILK3Jn40rvoR7bse6G2Zvg9InA2VS/q9LRb5ewPxg7Ovj4o6LV8fQCccuy2gWzNj"
                       + "PIr5uefG/69y460JPxg8/H+W9kEI8g3MgB+DfKAwuxDkAwG9pzwPcYO3ctaxyLw+31s36q7iGwx4JdF9+MW6bAv6fUpdkvvRC5W/XD7Ny7zN0+OprESeZM00m/VHTWjPhnDgpV2ve/477PlbPYDEuHkNvspKiqSatqZYqhenvayL5bRYZWV3tJ2GtxQIjMOC7H7zNF8RUyCqd6O6TTeblgke37VQO+S8afjBWupmRjEK+/ePZ4v9iTKqPZgt++EPhVmMr+OjYD/7WWGaDRm9b5xphnPr/a42JXt/KIxjlv37sfp7yfYPh1F+GIxyS4n/YfJIPMX1Q2WPYb/EsYnfxmeX4PP/n7LN5pTxzyn73LB080NhIw+H/5dqmq/BvN8Q6/yQNM77cugPT+uIM2xT6ab/btq7xzSanXf4fpQ6v9pnIEmYk38/qWhuxS1nh7o7f12YzofuAXZfxaCbb2/uwqqlXg/2m1gH1s27Cb7z7Pq0sV9FCWRXVm/qIhCRXi/Bt7GOvAb9vjyW6U+LREWp16YzOZGwKRD67vzy+p37sMf7HUXlvcR/d9VNiPwtBtb34iODu8HVD9HszH64RL1pgB2+5BftZx88UN/rjAxx0Cl93zn4ORhSwO/DQ9ugjoeskod28PnP2ZC7Vj0y3I2G/4Nm82uQZsMQewu69rvHd0Vp6Qf0Z2/hlmzfeonEkfz1NG+KCwfiMcFc5uyaOKCmzdnyvDK2t4ORadLJNX2RtxklqrLjui3Os2lLX0/zpuEZ/cmsXFOTU1p4m50tv1y3q3VLQ84Xk/LaJwaM+Kb+H9/t4fz4yxX+8laqv/4QCM0CubYvl0/WRTmzeD+LpMoGQMA70CQl5rJFsvLi2kJ6US1vCUjJ99Q4NW/yxaokYM2Xy9fZZT6M2800DCn2+GmRXdTZolEY7n36k9hvtnh39P8EAAD///7O71zfVgAA"; }
        }
    }
}
